language: php
php:
  - 5.6
  - 7.2

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - composer test

notifications:
  email:
    on_success: never
    on_failure: always
